spring:
  profiles:
    active: composite
  cloud:
    config:
      server:
        profile: test
        label: sample-config
        composite:
        - type: aws
          bucket: srikanth-sg-demo-config-server
          region: us-east-1
        bootstrap: true
